// ============================================================
//  大侠模拟器 · 核心数据库
//  时代背景：神雕侠侣年间，郭靖守襄阳
// ============================================================

const DATA = {

// ─────────────────────────────────────────────
//  人物特质
//  cost > 0 = 正面特质（花费分数）
//  cost < 0 = 负面特质（返还分数）
//  初始分数 20，最终剩余必须 >= 0
// ─────────────────────────────────────────────
TRAITS: [

  // ══ 天赋类（正面，高消耗）══
  { id:'t_genius',    name:'武学奇才',  cost:6, tag:'天赋',
    desc:'百年难遇的武学天才，修炼速度是常人三倍，悟性与内力远超同龄人',
    bonus:{ perception:20, innerPower:15, swordSkill:10 } },
  { id:'t_inner',     name:'先天真气',  cost:5, tag:'天赋',
    desc:'娘胎里便带着一股先天真气，内力根基远超常人，修炼内功事半功倍',
    bonus:{ innerPower:25, endurance:10 } },
  { id:'t_strong',    name:'天生神力',  cost:4, tag:'天赋',
    desc:'生来力大无穷，臂力惊人，习练外功招式事半功倍',
    bonus:{ strength:20, endurance:10, hp:15 } },
  { id:'t_agile',     name:'身轻如燕',  cost:4, tag:'天赋',
    desc:'骨骼轻盈，筋骨柔韧，天生适合轻功身法，一学便会',
    bonus:{ agility:20, speed:12 } },
  { id:'t_memory',    name:'过目不忘',  cost:4, tag:'天赋',
    desc:'见过的武功招式过目不忘，举一反三，学武速度极快',
    bonus:{ perception:18, luck:8 } },
  { id:'t_sword',     name:'剑道天赋',  cost:3, tag:'天赋',
    desc:'与剑有缘，初次握剑便如老友重逢，习剑法如鱼得水',
    bonus:{ swordSkill:18, agility:8 } },
  { id:'t_poison',    name:'百毒不侵',  cost:3, tag:'天赋',
    desc:'天生对毒素有极强抵抗力，中毒后恢复极快，甚至以毒养身',
    bonus:{ endurance:12, hp:20, luck:5 } },
  { id:'t_lucky',     name:'鸿运当头',  cost:3, tag:'天赋',
    desc:'天生好运，奇遇频发，总能在危难时化险为夷',
    bonus:{ luck:22 } },

  // ══ 体魄类（正面，中等消耗）══
  { id:'t_tough',     name:'铁骨铮铮',  cost:3, tag:'体魄',
    desc:'体魄强健，气血充沛，受伤后恢复极快，耐力远超常人',
    bonus:{ hp:35, endurance:15 } },
  { id:'t_fast',      name:'疾如闪电',  cost:3, tag:'体魄',
    desc:'天生反应极快，出手速度惊人，先发制人的能力极强',
    bonus:{ speed:18, agility:10 } },
  { id:'t_endure',    name:'坚韧不拔',  cost:2, tag:'体魄',
    desc:'意志如铁，修炼不辍，越挫越勇，逆境中成长更快',
    bonus:{ endurance:18, innerPower:8 } },
  { id:'t_healthy',   name:'身强体壮',  cost:2, tag:'体魄',
    desc:'从不生病，体质极佳，气血旺盛，修炼时消耗体力更少',
    bonus:{ hp:25, endurance:12 } },

  // ══ 心性类（正面，中等消耗）══
  { id:'t_kind',      name:'悲天悯人',  cost:3, tag:'心性',
    desc:'心怀苍生，侠义为先，正道中人对你天然亲近，声望提升更快',
    bonus:{ morality:20, reputation:12, charm:8 } },
  { id:'t_handsome',  name:'相貌堂堂',  cost:3, tag:'心性',
    desc:'仪表不凡，气宇轩昂，初见便令人心生好感，社交事半功倍',
    bonus:{ charm:20, reputation:8 } },
  { id:'t_calm',      name:'心如止水',  cost:2, tag:'心性',
    desc:'处变不惊，临危不乱，战斗中不受恐惧影响，内功修炼更稳',
    bonus:{ innerPower:12, perception:10, endurance:8 } },
  { id:'t_brave',     name:'胆大心细',  cost:2, tag:'心性',
    desc:'敢于冒险，又不失谨慎，探索奇遇时成功率更高',
    bonus:{ luck:12, perception:8 } },

  // ══ 负面特质（返还分数）══
  { id:'t_weak',      name:'体弱多病',  cost:-2, tag:'缺陷',
    desc:'自幼体弱，三天两头生病，气血不足，修炼时体力消耗更大',
    bonus:{ hp:-25, endurance:-12 } },
  { id:'t_dull',      name:'资质平庸',  cost:-2, tag:'缺陷',
    desc:'悟性一般，学武比常人慢一倍，但胜在踏实肯干',
    bonus:{ perception:-15, luck:-5 } },
  { id:'t_poor_start', name:'一贫如洗', cost:-2, tag:'缺陷',
    desc:'身无分文，连盘缠都凑不齐，初始银两极少',
    bonus:{ gold:-40 } },
  { id:'t_ugly',      name:'其貌不扬',  cost:-1, tag:'缺陷',
    desc:'相貌平平，甚至有些丑陋，初次见面总让人印象不佳',
    bonus:{ charm:-15, reputation:-5 } },
  { id:'t_coward',    name:'胆小如鼠',  cost:-2, tag:'缺陷',
    desc:'天生胆怯，遇到强敌容易退缩，战斗中容易失误',
    bonus:{ luck:-8, strength:-8, endurance:-5 } },
  { id:'t_arrogant',  name:'目中无人',  cost:-1, tag:'缺陷',
    desc:'自视甚高，不把他人放在眼里，难以结交朋友，好感度提升更慢',
    bonus:{ charm:-12, reputation:-8 } },
  { id:'t_wine',      name:'嗜酒如命',  cost:-2, tag:'缺陷',
    desc:'酒瘾极大，每月必须花钱买酒，但酒后武功反而大进',
    bonus:{ strength:10, innerPower:8, gold:-35 } },
  { id:'t_cruel',     name:'心狠手辣',  cost:-1, tag:'缺陷',
    desc:'行事果决，不留余地，正道人士对你天然排斥，道德值难以提升',
    bonus:{ strength:10, evil:15, morality:-15, charm:-8 } },
  { id:'t_stubborn2', name:'固执己见',  cost:-1, tag:'缺陷',
    desc:'认准的事九头牛都拉不回，拜师时师傅更难接受你，但修炼更专注',
    bonus:{ innerPower:5, perception:-8 } },
  { id:'t_sickly',    name:'先天不足',  cost:-3, tag:'缺陷',
    desc:'先天内力亏损，修炼内功比常人难上数倍，但外功反而更强',
    bonus:{ innerPower:-20, strength:12, endurance:8 } },
  { id:'t_jinx',      name:'天生霉星',  cost:-2, tag:'缺陷',
    desc:'倒霉体质，奇遇总是擦肩而过，但也因此磨砺出超强意志',
    bonus:{ luck:-18, endurance:10 } },
  { id:'t_cold',      name:'冷若冰霜',  cost:-1, tag:'缺陷',
    desc:'不苟言笑，拒人千里，令人难以亲近，但气场令敌人心生畏惧',
    bonus:{ charm:-15, strength:8, reputation:5 } },
],

// ─────────────────────────────────────────────
//  背景特质
//  同样采用分数制，细分为多个类别
//  每类最多选1个（出身/经历/际遇各选1个，共3个）
// ─────────────────────────────────────────────
BACKGROUNDS: [

  // ══ 出身类（家世背景）══
  { id:'b_noble',     name:'书香门第',  cost:3, tag:'出身',
    desc:'出身书香世家，自幼饱读诗书，见识广博，家中藏书万卷，初始金钱充裕',
    bonus:{ gold:80, perception:12, charm:8 } },
  { id:'b_military',  name:'将门虎子',  cost:3, tag:'出身',
    desc:'出身将门世家，自幼习武，家传刀法已有基础，父辈在军中颇有威望',
    bonus:{ strength:15, endurance:12, swordSkill:8, gold:40 } },
  { id:'b_merchant',  name:'富商之后',  cost:3, tag:'出身',
    desc:'家境殷实，从不为钱发愁，人脉广泛，初始银两丰厚',
    bonus:{ gold:120, charm:10, luck:8 } },
  { id:'b_official',  name:'官宦之后',  cost:2, tag:'出身',
    desc:'父辈为官，自幼见惯官场，人情世故娴熟，在朝廷中有些关系',
    bonus:{ charm:12, gold:60, reputation:12 } },
  { id:'b_jianghu',   name:'江湖遗孤',  cost:2, tag:'出身',
    desc:'父母皆为江湖人，自幼耳濡目染，对江湖规矩了如指掌，有些武学基础',
    bonus:{ swordSkill:12, reputation:15, gold:20 } },
  { id:'b_monk',      name:'寺庙出身',  cost:2, tag:'出身',
    desc:'自幼在寺庙长大，青灯古佛，内功根基扎实，心性平和',
    bonus:{ innerPower:20, morality:15, gold:-10 } },
  { id:'b_nomad',     name:'塞外牧民',  cost:1, tag:'出身',
    desc:'来自塞外草原，自幼骑马射箭，体魄强健，但对中原江湖规矩不熟',
    bonus:{ strength:18, endurance:15, agility:8, reputation:-5 } },
  { id:'b_poor',      name:'贫苦人家',  cost:-1, tag:'出身',
    desc:'自幼贫苦，食不果腹，但磨砺出坚韧意志，对钱财格外珍惜',
    bonus:{ endurance:15, strength:8, gold:-35 } },
  { id:'b_orphan',    name:'孤苦伶仃',  cost:-2, tag:'出身',
    desc:'自幼父母双亡，流浪街头，无依无靠，但也因此心志坚定，不惧艰辛',
    bonus:{ endurance:20, strength:10, gold:-45, charm:-5 } },
  { id:'b_slave',     name:'奴仆出身',  cost:-2, tag:'出身',
    desc:'曾为人奴仆，饱受欺凌，心中积怨，但也练就了察言观色的本领',
    bonus:{ perception:10, agility:10, gold:-30, morality:-10, evil:10 } },

  // ══ 经历类（成长经历）══
  { id:'e_study',     name:'苦读武典',  cost:3, tag:'经历',
    desc:'少年时遍读武学典籍，虽未实践，但理论基础扎实，学武时领悟更快',
    bonus:{ perception:15, innerPower:10, swordSkill:8 } },
  { id:'e_travel',    name:'游历四方',  cost:2, tag:'经历',
    desc:'少年时便独自游历江湖，见多识广，结交了不少朋友，声望略有基础',
    bonus:{ perception:12, charm:10, reputation:15, luck:5 } },
  { id:'e_army',      name:'从军历练',  cost:2, tag:'经历',
    desc:'曾在军中历练数年，学得一身实战本领，纪律严明，体魄强健',
    bonus:{ strength:15, endurance:12, swordSkill:10 } },
  { id:'e_doctor',    name:'学医问药',  cost:2, tag:'经历',
    desc:'曾跟随郎中学医，懂得疗伤之术，识得百草，受伤后恢复更快',
    bonus:{ hp:25, endurance:10, perception:8, gold:15 } },
  { id:'e_merchant2', name:'行商走镖',  cost:1, tag:'经历',
    desc:'曾随商队走镖，见识了江湖险恶，练就了一身防身本领，积攒了些银两',
    bonus:{ agility:10, strength:8, gold:50, luck:5 } },
  { id:'e_thief',     name:'绿林经历',  cost:1, tag:'经历',
    desc:'曾混迹绿林，身手敏捷，消息灵通，但留下了些许污点',
    bonus:{ agility:15, luck:12, evil:8, gold:30, reputation:-5 } },
  { id:'e_prison',    name:'牢狱之灾',  cost:-1, tag:'经历',
    desc:'曾身陷囹圄，在牢中苦熬数年，意志磨砺如铁，但声名有损',
    bonus:{ endurance:18, strength:10, reputation:-15, gold:-20 } },
  { id:'e_betrayed',  name:'遭人背叛',  cost:-1, tag:'经历',
    desc:'曾被至亲好友背叛，心灰意冷，从此不轻易信人，但也更加独立坚强',
    bonus:{ endurance:12, perception:8, charm:-12, morality:-8 } },
  { id:'e_disaster',  name:'家道中落',  cost:-2, tag:'经历',
    desc:'家族曾遭横祸，一夜之间从富贵跌入贫困，但也因此磨砺出不屈意志',
    bonus:{ endurance:15, strength:8, gold:-50, reputation:-10 } },

  // ══ 际遇类（特殊机缘）══
  { id:'r_secret',    name:'得遇秘籍',  cost:4, tag:'际遇',
    desc:'少年时偶然得到一本残缺武学秘籍，虽不完整，但已让你武学基础远超同龄人',
    bonus:{ innerPower:18, swordSkill:12, perception:10 } },
  { id:'r_master',    name:'高人点拨',  cost:3, tag:'际遇',
    desc:'曾被一位隐世高人偶然点拨，虽只是只言片语，却让你武学境界豁然开朗',
    bonus:{ innerPower:15, perception:15, luck:8 } },
  { id:'r_treasure',  name:'意外横财',  cost:2, tag:'际遇',
    desc:'少年时意外发现一处藏宝，虽大部分已散尽，但仍留有不少银两傍身',
    bonus:{ gold:100, luck:10 } },
  { id:'r_hero',      name:'英雄救美',  cost:2, tag:'际遇',
    desc:'曾路见不平，出手相救，此事在当地传为美谈，声望与道德均有基础',
    bonus:{ reputation:20, morality:15, charm:10 } },
  { id:'r_poison2',   name:'奇毒淬体',  cost:1, tag:'际遇',
    desc:'少年时曾中一种奇毒，虽九死一生，但毒素与体内真气融合，体质大变',
    bonus:{ endurance:20, hp:15, innerPower:10, luck:-5 } },
  { id:'r_enemy',     name:'仇家追杀',  cost:-1, tag:'际遇',
    desc:'少年时便有仇家追杀，在逃亡中练就了一身逃跑本领，但也留下了心理阴影',
    bonus:{ agility:15, speed:10, luck:-10, charm:-8 } },
  { id:'r_curse',     name:'身负诅咒',  cost:-2, tag:'际遇',
    desc:'据说你出生时有异象，被人说是不祥之人，但也因此激发了你证明自己的决心',
    bonus:{ endurance:12, innerPower:8, reputation:-15, charm:-10 } },
  { id:'r_debt',      name:'背负债务',  cost:-2, tag:'际遇',
    desc:'家中欠下巨债，债主时常上门催讨，不得不拼命赚钱还债',
    bonus:{ gold:-60, endurance:10, strength:5 } },
],

// ─────────────────────────────────────────────
//  武学体系
// ─────────────────────────────────────────────
MARTIAL_ARTS: [
  // 内功
  { id:'m_jiuyang',   name:'九阳神功',   type:'inner',   tier:5, sect:'少林',
    desc:'天下至阳至刚内功，修炼后百毒不侵，内力绵绵不绝',
    require:{ innerPower:80, perception:60 },
    effect:{ innerPower:50, endurance:30, hp:40 } },
  { id:'m_jiuyin',    name:'九阴真经',   type:'inner',   tier:5, sect:'无',
    desc:'武林至高秘典，内外兼修，威力无穷',
    require:{ innerPower:70, perception:70 },
    effect:{ innerPower:45, agility:25, swordSkill:20 } },
  { id:'m_beiming',   name:'北冥神功',   type:'inner',   tier:5, sect:'逍遥派',
    desc:'吸人内力为己用，修炼者内力深不可测',
    require:{ innerPower:60, perception:65 },
    effect:{ innerPower:60, hp:20 } },
  { id:'m_yijin',     name:'易筋经',     type:'inner',   tier:4, sect:'少林',
    desc:'少林镇寺神功，修炼后筋骨脱胎换骨',
    require:{ innerPower:50, endurance:50 },
    effect:{ innerPower:30, strength:25, endurance:20 } },
  { id:'m_zixia',     name:'紫霞神功',   type:'inner',   tier:4, sect:'华山',
    desc:'华山派内功心法，刚柔并济',
    require:{ innerPower:40, perception:40 },
    effect:{ innerPower:25, swordSkill:15, agility:10 } },
  { id:'m_chunyang',  name:'纯阳无极功', type:'inner',   tier:3, sect:'全真',
    desc:'全真教内功，修炼后内力纯正',
    require:{ innerPower:30, morality:20 },
    effect:{ innerPower:20, endurance:15 } },
  { id:'m_basic',     name:'基础吐纳功', type:'inner',   tier:1, sect:'无',
    desc:'最基础的内功心法，人人可学',
    require:{},
    effect:{ innerPower:8, endurance:5 } },

  // 剑法
  { id:'m_duli',      name:'独孤九剑',   type:'sword',   tier:5, sect:'无',
    desc:'天下第一剑法，无招胜有招，破尽天下武功',
    require:{ swordSkill:80, perception:80, agility:60 },
    effect:{ swordSkill:60, agility:20 } },
  { id:'m_taiji',     name:'太极剑法',   type:'sword',   tier:4, sect:'武当',
    desc:'以柔克刚，四两拨千斤',
    require:{ swordSkill:50, innerPower:50 },
    effect:{ swordSkill:30, agility:15, innerPower:10 } },
  { id:'m_huashan',   name:'华山剑法',   type:'sword',   tier:3, sect:'华山',
    desc:'华山派正宗剑法，刚猛凌厉',
    require:{ swordSkill:30, innerPower:25 },
    effect:{ swordSkill:20, strength:8 } },
  { id:'m_wudang',    name:'武当长剑',   type:'sword',   tier:3, sect:'武当',
    desc:'武当派剑法，正大光明',
    require:{ swordSkill:25, morality:15 },
    effect:{ swordSkill:18, innerPower:8 } },
  { id:'m_basic_sword', name:'基础剑术', type:'sword',   tier:1, sect:'无',
    desc:'最基础的剑术，初学者必修',
    require:{},
    effect:{ swordSkill:8 } },

  // 掌法/拳法
  { id:'m_jianglong', name:'降龙十八掌', type:'palm',    tier:5, sect:'丐帮',
    desc:'丐帮镇帮绝学，刚猛无匹，天下第一掌法',
    require:{ strength:70, innerPower:60, endurance:50 },
    effect:{ strength:40, innerPower:20, hp:20 } },
  { id:'m_shaolin',   name:'少林拳法',   type:'palm',    tier:3, sect:'少林',
    desc:'少林七十二绝技之基础，刚猛有力',
    require:{ strength:30, endurance:30 },
    effect:{ strength:20, endurance:15 } },
  { id:'m_tianshan',  name:'天山折梅手', type:'palm',    tier:4, sect:'逍遥派',
    desc:'逍遥派绝学，以柔克刚，变化无穷',
    require:{ agility:50, perception:50 },
    effect:{ agility:25, strength:15, innerPower:10 } },

  // 轻功
  { id:'m_lingbo',    name:'凌波微步',   type:'qinggong', tier:5, sect:'逍遥派',
    desc:'天下第一轻功，步法变化如鬼魅',
    require:{ agility:70, innerPower:60, perception:60 },
    effect:{ agility:50, speed:30 } },
  { id:'m_tianzhan',  name:'梯云纵',     type:'qinggong', tier:4, sect:'武当',
    desc:'武当轻功，纵跃如飞',
    require:{ agility:40, innerPower:35 },
    effect:{ agility:25, speed:15 } },
  { id:'m_caoyuan',   name:'草上飞',     type:'qinggong', tier:2, sect:'无',
    desc:'江湖常见轻功，轻盈灵活',
    require:{ agility:20 },
    effect:{ agility:12, speed:8 } },

  // 暗器
  { id:'m_anqi',      name:'弹指神通',   type:'hidden',  tier:4, sect:'桃花岛',
    desc:'黄药师绝学，以内力弹出暗器，威力惊人',
    require:{ innerPower:50, agility:40, perception:50 },
    effect:{ agility:20, innerPower:10 } },
  { id:'m_feihua',    name:'飞花摘叶',   type:'hidden',  tier:3, sect:'无',
    desc:'以花叶为暗器，随手拈来皆是武器',
    require:{ innerPower:40, agility:35 },
    effect:{ agility:15, innerPower:8 } },

  // 邪功
  { id:'m_xingxiu',   name:'星宿神功',   type:'evil',    tier:4, sect:'星宿派',
    desc:'星宿老怪所创，阴毒无比，配合毒药威力大增',
    require:{ evil:30, innerPower:40 },
    effect:{ innerPower:25, evil:15, charm:-10 } },
  { id:'m_sunflower', name:'葵花宝典',   type:'evil',    tier:5, sect:'无',
    desc:'武功奇书，修炼者需自宫，威力无与伦比',
    require:{ innerPower:80, evil:20 },
    effect:{ innerPower:60, agility:30, swordSkill:30, charm:-20 } },
  { id:'m_huagong',   name:'化功大法',   type:'evil',    tier:4, sect:'明教',
    desc:'明教秘传，可化解他人内力',
    require:{ innerPower:50, evil:15 },
    effect:{ innerPower:35, endurance:15 } },
],

// ─────────────────────────────────────────────
//  神兵利器
// ─────────────────────────────────────────────
WEAPONS: [
  { id:'w_yitian',    name:'倚天剑',     tier:5, type:'sword',
    desc:'削铁如泥，天下至利之剑，内藏九阴真经',
    bonus:{ swordSkill:30, strength:15 }, location:'unknown' },
  { id:'w_tulong',    name:'屠龙刀',     tier:5, type:'blade',
    desc:'号令天下，莫敢不从，内藏武穆遗书',
    bonus:{ strength:30, reputation:20 }, location:'unknown' },
  { id:'w_xuantiexue', name:'玄铁重剑',  tier:4, type:'sword',
    desc:'重剑无锋，大巧不工，以力破巧',
    bonus:{ strength:25, swordSkill:15 }, location:'古墓' },
  { id:'w_bihaochao', name:'碧海潮生曲', tier:4, type:'flute',
    desc:'桃花岛传世之宝，以音律伤人',
    bonus:{ innerPower:20, charm:15 }, location:'桃花岛' },
  { id:'w_ruyi',      name:'如意金箍棒', tier:3, type:'staff',
    desc:'传说中的神器，重逾千斤',
    bonus:{ strength:20, endurance:10 }, location:'少林' },
  { id:'w_zhanlu',    name:'湛卢剑',     tier:3, type:'sword',
    desc:'仁者之剑，剑气凛然',
    bonus:{ swordSkill:20, morality:10 }, location:'武当' },
  { id:'w_puhong',    name:'朴刀',       tier:1, type:'blade',
    desc:'普通朴刀，江湖常见兵器',
    bonus:{ strength:5 }, location:'铁匠铺' },
  { id:'w_common_sword', name:'普通长剑', tier:1, type:'sword',
    desc:'普通长剑，初学者常用',
    bonus:{ swordSkill:5 }, location:'铁匠铺' },
],

// ─────────────────────────────────────────────
//  NPC 人物（金庸宇宙）
// ─────────────────────────────────────────────
NPCS: [
  // 神雕侠侣人物
  { id:'n_guojing',   name:'郭靖',    title:'郭大侠',   sect:'丐帮',  align:'good',
    desc:'侠之大者，为国为民，镇守襄阳',
    location:'襄阳', power:95, favor:0,
    canTeach:'m_jianglong', canRecruit:false,
    dialog:['为国为民，侠之大者。','你可愿为守护襄阳出一份力？','习武之人，当以天下苍生为念。'] },
  { id:'n_huangrong',  name:'黄蓉',   title:'黄帮主',   sect:'丐帮',  align:'good',
    desc:'聪慧机敏，丐帮帮主，郭靖之妻',
    location:'襄阳', power:85, favor:0,
    canTeach:'m_anqi', canRecruit:false,
    dialog:['你这人倒有几分意思。','丐帮的事，我自有主张。','桃花岛的武功，可不是随便传人的。'] },
  { id:'n_yangguo',   name:'杨过',    title:'神雕大侠', sect:'无',    align:'neutral',
    desc:'情深义重，武功盖世，独臂神雕侠',
    location:'古墓', power:98, favor:0,
    canTeach:'m_xuantiexue', canRecruit:false,
    dialog:['我行我素，不受任何约束。','小龙女是我此生唯一。','玄铁重剑，重剑无锋，大巧不工。'] },
  { id:'n_xiaolongnv', name:'小龙女', title:'姑姑',     sect:'古墓派', align:'neutral',
    desc:'冰清玉洁，古墓派传人，杨过之妻',
    location:'古墓', power:90, favor:0,
    canTeach:null, canRecruit:false,
    dialog:['过儿，你来了。','古墓之中，清净无为。','世间纷扰，不如归去。'] },
  { id:'n_jinlun',    name:'金轮法王', title:'法王',    sect:'蒙古',  align:'evil',
    desc:'蒙古国师，武功深不可测，野心勃勃',
    location:'蒙古大营', power:92, favor:0,
    canTeach:'m_yijin', canRecruit:true,
    dialog:['蒙古铁骑，天下无敌。','识时务者为俊杰，何不归顺大汗？','你的武功，倒有几分意思。'] },
  { id:'n_liuyingzhou', name:'李莫愁', title:'赤练仙子', sect:'古墓派', align:'evil',
    desc:'心狠手辣，赤练神掌，情伤之后性情大变',
    location:'江湖', power:75, favor:0,
    canTeach:null, canRecruit:true,
    dialog:['问世间情为何物，直教生死相许。','你若惹了我，休想活命。','哼，男人没一个好东西。'] },
  { id:'n_yinggu',    name:'瑛姑',    title:'瑛姑',     sect:'无',    align:'neutral',
    desc:'一灯大师旧情人，精通奇门数术',
    location:'黑沼', power:60, favor:0,
    canTeach:null, canRecruit:false,
    dialog:['我这一生，皆是错误。','数术之道，可知天命。','你来此地，所为何事？'] },

  // 天龙八部人物（年迈版）
  { id:'n_xuzhu',     name:'虚竹',    title:'虚竹大师', sect:'少林/逍遥派', align:'good',
    desc:'逍遥派掌门，少林弟子出身，武功深不可测',
    location:'少林', power:96, favor:0,
    canTeach:'m_beiming', canRecruit:false,
    dialog:['阿弥陀佛，施主有礼了。','逍遥派的武功，非有缘人不可传。','老衲在少林修行多年，尘缘已了。'] },
  { id:'n_duan',      name:'段誉',    title:'段皇爷',   sect:'大理',  align:'good',
    desc:'大理皇帝，六脉神剑与凌波微步传人',
    location:'大理', power:88, favor:0,
    canTeach:'m_lingbo', canRecruit:false,
    dialog:['大理段氏，以仁义治国。','六脉神剑，非段氏子弟不可传。','施主若有难，段某愿效犬马之劳。'] },
  { id:'n_tianshan',  name:'天山童姥', title:'童姥',    sect:'逍遥派', align:'evil',
    desc:'逍遥派长老，修炼不老童功，性情乖戾',
    location:'天山', power:94, favor:0,
    canTeach:'m_tianshan', canRecruit:false,
    dialog:['老身的武功，岂是你能学的？','天山之上，唯我独尊。','你若能让老身满意，或许可以传你一招半式。'] },

  // 江湖散人
  { id:'n_laotou',    name:'老叫花',  title:'老叫花',   sect:'丐帮',  align:'good',
    desc:'丐帮老乞丐，看似落魄，实则深藏不露',
    location:'小镇', power:40, favor:0,
    canTeach:'m_basic', canRecruit:false,
    dialog:['小娃娃，给老头儿几文钱吧。','哈哈，老头儿我也曾是江湖中人。','你有慧根，老头儿教你几招。'] },
  { id:'n_blacksmith', name:'铁匠王',  title:'王铁匠',  sect:'无',    align:'neutral',
    desc:'小镇铁匠，打造兵器一流',
    location:'小镇', power:10, favor:0,
    canTeach:null, canRecruit:false,
    dialog:['要打什么兵器，尽管说。','好铁出好刀，价钱不便宜。','这把剑，是我的得意之作。'] },
  { id:'n_innkeeper',  name:'掌柜老陈', title:'陈掌柜', sect:'无',    align:'neutral',
    desc:'小镇客栈掌柜，消息灵通',
    location:'小镇', power:5, favor:0,
    canTeach:null, canRecruit:false,
    dialog:['客官，打尖还是住店？','江湖上的事，老夫知道不少。','最近江湖上不太平啊。'] },
  { id:'n_beauty',    name:'林若雪',  title:'林姑娘',   sect:'无',    align:'good',
    desc:'小镇大夫之女，温柔善良，略懂医术',
    location:'小镇', power:8, favor:0,
    canTeach:null, canRecruit:true, canMarry:true,
    dialog:['公子有礼了。','父亲说，行医救人是最大的善事。','江湖险恶，公子多加小心。'] },
  { id:'n_merchant',  name:'赵员外',  title:'赵员外',   sect:'无',    align:'neutral',
    desc:'小镇富商，财大气粗，有些任务需要他',
    location:'小镇', power:15, favor:0,
    canTeach:null, canRecruit:false,
    dialog:['有钱能使鬼推磨。','这笔买卖，对你我都有好处。','你若帮我办成此事，重金酬谢。'] },
  { id:'n_wanderer',  name:'流浪剑客', title:'剑客',    sect:'无',    align:'neutral',
    desc:'行走江湖的剑客，武功不俗，可以切磋',
    location:'江湖', power:35, favor:0,
    canTeach:'m_basic_sword', canRecruit:true,
    dialog:['江湖路远，以剑为伴。','你若想学剑，先过我这一关。','切磋切磋，不打不相识。'] },
  { id:'n_monk',      name:'慧明和尚', title:'慧明',    sect:'少林',  align:'good',
    desc:'少林寺游方僧人，武功扎实',
    location:'江湖', power:45, favor:0,
    canTeach:'m_shaolin', canRecruit:false,
    dialog:['阿弥陀佛，施主有礼。','少林武功，以戒律为先。','施主若有向佛之心，可来少林一叙。'] },
  { id:'n_evil_man',  name:'黑风双煞', title:'双煞',    sect:'魔教',  align:'evil',
    desc:'魔教杀手，心狠手辣，专门劫道',
    location:'江湖', power:50, favor:0,
    canTeach:null, canRecruit:true,
    dialog:['把钱留下，留你全尸。','魔教行事，不留活口。','你若投靠魔教，荣华富贵少不了你的。'] },
],

// ─────────────────────────────────────────────
//  门派 / 帮派 / 朝廷
// ─────────────────────────────────────────────
SECTS: [
  {
    id:'s_shaolin',   name:'少林寺',   align:'good',   type:'sect',
    desc:'武林泰山北斗，天下武功出少林',
    location:'嵩山', require:{ morality:20, reputation:30 },
    ranks:['俗家弟子','记名弟子','入室弟子','执事僧','长老','方丈'],
    rankReq:[0,200,500,1000,2000,5000],
    teachable:['m_yijin','m_shaolin','m_basic'],
    benefits:['声望+5/月','可学少林武功','少林庇护'],
  },
  {
    id:'s_wudang',    name:'武当派',   align:'good',   type:'sect',
    desc:'武当七侠，正道领袖',
    location:'武当山', require:{ morality:15, reputation:20 },
    ranks:['外门弟子','内门弟子','亲传弟子','执事','长老','掌门'],
    rankReq:[0,150,400,800,1800,4000],
    teachable:['m_chunyang','m_wudang','m_tianzhan'],
    benefits:['声望+4/月','可学武当武功'],
  },
  {
    id:'s_huashan',   name:'华山派',   align:'good',   type:'sect',
    desc:'华山论剑发源地，剑气书香两派',
    location:'华山', require:{ swordSkill:20, reputation:15 },
    ranks:['外门弟子','内门弟子','亲传弟子','执事','长老','掌门'],
    rankReq:[0,100,300,700,1500,3500],
    teachable:['m_zixia','m_huashan'],
    benefits:['声望+3/月','可学华山武功'],
  },
  {
    id:'s_gaibang',   name:'丐帮',     align:'good',   type:'gang',
    desc:'天下第一大帮，消息最为灵通',
    location:'各地', require:{ reputation:25 },
    ranks:['新入帮','一袋弟子','三袋弟子','五袋弟子','七袋弟子','九袋长老','副帮主','帮主'],
    rankReq:[0,50,150,350,700,1500,3000,6000],
    teachable:['m_jianglong'],
    benefits:['消息+','声望+3/月','可学降龙十八掌'],
  },
  {
    id:'s_mingjiao',  name:'明教',     align:'evil',   type:'gang',
    desc:'魔教之首，行事神秘，追求力量',
    location:'光明顶', require:{ evil:20 },
    ranks:['普通教众','锐金旗','洪水旗','烈火旗','厚土旗','巨木旗','五行旗使','护教法王','左右使者','教主'],
    rankReq:[0,80,200,450,900,1800,3500,6000,10000,20000],
    teachable:['m_huagong','m_basic'],
    benefits:['武功资源+','邪道加成'],
  },
  {
    id:'s_xingxiu',   name:'星宿派',   align:'evil',   type:'sect',
    desc:'星宿老怪丁春秋所创，阴毒无比',
    location:'星宿海', require:{ evil:30 },
    ranks:['星宿弟子','星宿使者','星宿长老','星宿大长老','教主'],
    rankReq:[0,100,300,800,2000],
    teachable:['m_xingxiu'],
    benefits:['邪道加成','毒术+'],
  },
  {
    id:'s_court',     name:'朝廷司武监', align:'neutral', type:'court',
    desc:'朝廷武官机构，以秩序为先',
    location:'临安', require:{ reputation:40, morality:10 },
    ranks:['武监学员','武监校尉','武监百户','武监千户','武监指挥','武监都督','司武监正使'],
    rankReq:[0,200,500,1000,2000,4000,8000],
    teachable:[],
    benefits:['俸禄+','官方庇护','朝廷资源'],
  },
],

// ─────────────────────────────────────────────
//  地点
// ─────────────────────────────────────────────
LOCATIONS: [
  { id:'l_town',      name:'清风镇',   type:'town',    danger:0,
    desc:'一个宁静的小镇，是许多江湖人的起点',
    actions:['rest','work','train','talk','shop','quest'] },
  { id:'l_xiangyang', name:'襄阳城',   type:'city',    danger:2,
    desc:'郭靖镇守的英雄之城，战火纷飞',
    actions:['quest','fight','train','talk','shop','join_gaibang','join_court'] },
  { id:'l_shaolin',   name:'少林寺',   type:'sect',    danger:1,
    desc:'武林圣地，天下武功出少林',
    actions:['train','talk','join_shaolin','quest'] },
  { id:'l_wudang',    name:'武当山',   type:'sect',    danger:1,
    desc:'武当七侠，正道领袖',
    actions:['train','talk','join_wudang','quest'] },
  { id:'l_huashan',   name:'华山',     type:'sect',    danger:2,
    desc:'华山论剑之地，剑气纵横',
    actions:['train','talk','join_huashan','quest','explore'] },
  { id:'l_guigu',     name:'古墓',     type:'secret',  danger:3,
    desc:'古墓派所在，机关重重',
    actions:['explore','fight','talk'] },
  { id:'l_taohua',    name:'桃花岛',   type:'island',  danger:2,
    desc:'黄药师的桃花岛，机关阵法无数',
    actions:['explore','talk','quest'] },
  { id:'l_jianghu',   name:'江湖',     type:'wild',    danger:3,
    desc:'广阔江湖，奇遇与危险并存',
    actions:['explore','fight','quest','wander'] },
  { id:'l_mongol',    name:'蒙古大营', type:'enemy',   danger:5,
    desc:'蒙古军营，危机四伏',
    actions:['fight','spy','quest'] },
  { id:'l_dali',      name:'大理',     type:'city',    danger:1,
    desc:'大理国，段氏皇族所在',
    actions:['talk','quest','train','shop'] },
  { id:'l_tianshan',  name:'天山',     type:'wild',    danger:4,
    desc:'天山童姥所在，险峻无比',
    actions:['explore','fight','talk'] },
  { id:'l_guangming', name:'光明顶',   type:'sect',    danger:4,
    desc:'明教总坛，邪道圣地',
    actions:['train','talk','join_mingjiao','quest','fight'] },
],

// ─────────────────────────────────────────────
//  任务库
//  chain: 完成后解锁的下一个任务id
//  timeLimit: 时限（月），超时自动失败
//  repeatable: 可重复接取
// ─────────────────────────────────────────────
QUESTS: [
  // ══ 普通任务 ══
  { id:'q_escort',    name:'护送商队',  type:'normal',  difficulty:1,
    desc:'护送赵员外的商队安全抵达下一个城镇，路上可能遭遇山贼。',
    reward:{ gold:30, reputation:10, exp:20 },
    cost:{ time:1, energy:20 }, require:{},
    chain:'q_escort2' },

  { id:'q_escort2',   name:'护送要员',  type:'normal',  difficulty:2,
    desc:'赵员外感激你上次的帮助，这次委托你护送一位重要客商进京，报酬丰厚。',
    reward:{ gold:80, reputation:25, exp:40, favor:{ npc:'n_merchant', val:20 } },
    cost:{ time:2, energy:25 }, require:{ reputation:10 },
    chain:'q_escort3' },

  { id:'q_escort3',   name:'押送军饷',  type:'combat',  difficulty:3,
    desc:'朝廷委托押送一批军饷前往襄阳，沿途有蒙古细作觊觎，务必安全送达。',
    reward:{ gold:150, reputation:50, morality:10, exp:80 },
    cost:{ time:3, energy:40 }, require:{ reputation:30, strength:25 } },

  { id:'q_medicine',  name:'采集草药',  type:'normal',  difficulty:1,
    desc:'林大夫需要一些珍贵草药，请你去山中采集。',
    reward:{ gold:20, reputation:5, favor:{ npc:'n_beauty', val:15 }, exp:15, item:'i_herb' },
    cost:{ time:1, energy:15 }, require:{},
    chain:'q_medicine2' },

  { id:'q_medicine2', name:'寻找百年人参', type:'explore', difficulty:2,
    desc:'林姑娘说有位重病老人急需百年人参，深山中或许能找到，但山中危险重重。',
    reward:{ gold:40, reputation:15, favor:{ npc:'n_beauty', val:30 }, exp:30, item:'i_ginseng' },
    cost:{ time:2, energy:30 }, require:{},
    chain:'q_medicine3' },

  { id:'q_medicine3', name:'救治郭大侠',  type:'normal',  difficulty:2,
    desc:'郭大侠在守城中受了内伤，林姑娘请你协助寻找解药材料，此乃大义之举。',
    reward:{ gold:0, reputation:60, morality:20, favor:{ npc:'n_guojing', val:40 }, exp:60 },
    cost:{ time:2, energy:20 }, require:{} },

  { id:'q_bandit',    name:'剿灭山贼',  type:'combat',  difficulty:2,
    desc:'附近山上有一伙山贼，官府悬赏剿灭，活捉首领赏银加倍。',
    reward:{ gold:50, reputation:20, exp:40 },
    cost:{ time:2, energy:30 }, require:{ strength:20 },
    chain:'q_bandit2' },

  { id:'q_bandit2',   name:'山贼头目',  type:'combat',  difficulty:3,
    desc:'上次剿匪后，山贼头目亲自出马，纠集更多人马，扬言要报仇，必须将其彻底击溃。',
    reward:{ gold:100, reputation:40, exp:70 },
    cost:{ time:2, energy:40 }, require:{ strength:30 } },

  { id:'q_letter',    name:'传递书信',  type:'normal',  difficulty:1,
    desc:'帮郭大侠传递一封重要书信到武当山，务必亲手交给张真人。',
    reward:{ gold:10, reputation:15, favor:{ npc:'n_guojing', val:20 }, exp:10 },
    cost:{ time:3, energy:20 }, require:{},
    chain:'q_letter2' },

  { id:'q_letter2',   name:'秘密情报',  type:'stealth', difficulty:3,
    desc:'郭大侠有一份关于蒙古军部署的秘密情报，需要秘密送往临安朝廷，不能被蒙古细作发现。',
    reward:{ gold:60, reputation:40, morality:15, exp:60 },
    cost:{ time:4, energy:35 }, require:{ agility:25, perception:20 } },

  { id:'q_spy',       name:'刺探军情',  type:'stealth', difficulty:3,
    desc:'潜入蒙古大营，刺探军事部署，带回情报可获重赏。',
    reward:{ gold:80, reputation:30, exp:60 },
    cost:{ time:2, energy:40 }, require:{ agility:30 } },

  { id:'q_rescue',    name:'营救人质',  type:'combat',  difficulty:3,
    desc:'魔教绑架了无辜百姓，前去营救，时间紧迫！',
    reward:{ gold:60, reputation:40, morality:10, exp:50 },
    cost:{ time:2, energy:35 }, require:{ strength:30, swordSkill:20 },
    timeLimit: 6 },

  { id:'q_treasure',  name:'寻找宝藏',  type:'explore', difficulty:4,
    desc:'传说古墓中藏有前人留下的武学秘籍，但机关重重，需要极高的身法和悟性。',
    reward:{ gold:100, exp:80, randomWeapon:true },
    cost:{ time:3, energy:50 }, require:{ agility:40, perception:30 } },

  { id:'q_defend',    name:'协助守城',  type:'combat',  difficulty:4,
    desc:'蒙古大军来袭，协助郭大侠守卫襄阳，此乃侠义之举！',
    reward:{ gold:0, reputation:60, morality:20, exp:100 },
    cost:{ time:5, energy:60 }, require:{ strength:40, innerPower:30 },
    repeatable: true },

  { id:'q_assassin',  name:'暗杀任务',  type:'evil',    difficulty:3,
    desc:'魔教委托你暗杀一名官员，事成之后重金酬谢。',
    reward:{ gold:150, evil:20, exp:50 },
    cost:{ time:1, energy:30 }, require:{ evil:10 } },

  // ══ 时限任务（紧急）══
  { id:'q_urgent_herb', name:'【紧急】寻药救人', type:'normal', difficulty:2,
    desc:'【限时6个月】城中爆发瘟疫，急需大量草药，每耽误一天都有人命危在旦夕！',
    reward:{ gold:120, reputation:50, morality:25, exp:60 },
    cost:{ time:2, energy:30 }, require:{},
    timeLimit: 6 },

  { id:'q_urgent_defend', name:'【紧急】边境告急', type:'combat', difficulty:4,
    desc:'【限时4个月】蒙古军突袭边境小城，守军告急，需要立刻驰援！',
    reward:{ gold:0, reputation:80, morality:30, exp:120 },
    cost:{ time:3, energy:50 }, require:{ strength:35, innerPower:25 },
    timeLimit: 4 },
],

// ─────────────────────────────────────────────
//  I: 悬赏令模板（随机生成）
// ─────────────────────────────────────────────
BOUNTY_TEMPLATES: [
  { id:'bt_bandit',   name:'剿匪悬赏',   type:'combat',  difficulty:2,
    descTpl:'官府悬赏：击败盘踞{loc}的{enemy}，赏银{gold}两。',
    reward:{ gold:40, reputation:15 }, cost:{ time:1, energy:25 },
    require:{ strength:15 } },
  { id:'bt_escort',   name:'护镖悬赏',   type:'normal',  difficulty:1,
    descTpl:'镖局急招：护送货物从{loc}出发，安全送达赏银{gold}两。',
    reward:{ gold:25, reputation:8 }, cost:{ time:1, energy:15 },
    require:{} },
  { id:'bt_hunt',     name:'猎杀恶人',   type:'combat',  difficulty:3,
    descTpl:'江湖通缉：{enemy}作恶多端，击败者赏银{gold}两，声望大增。',
    reward:{ gold:80, reputation:30, morality:10 }, cost:{ time:2, energy:35 },
    require:{ strength:25 } },
  { id:'bt_explore',  name:'探路悬赏',   type:'explore', difficulty:2,
    descTpl:'商队急需：探明{loc}附近的安全路线，报酬{gold}两。',
    reward:{ gold:35, reputation:10 }, cost:{ time:2, energy:30 },
    require:{ agility:20 } },
],

// ─────────────────────────────────────────────
//  随机事件库
// ─────────────────────────────────────────────
EVENTS: [
  {
    id:'e_old_man',   name:'路遇高人',
    desc:'你在路上遇到一位白发老人，他似乎在等你。',
    choices:[
      { text:'上前行礼，恭敬问候',
        result:'老人微微一笑，传授你一套基础内功心法。',
        effect:{ innerPower:10, morality:5 } },
      { text:'视而不见，继续赶路',
        result:'你擦肩而过，错失良机。',
        effect:{} },
      { text:'试探老人武功深浅',
        result:'老人轻描淡写地化解你的试探，哈哈一笑而去。',
        effect:{ perception:5 } },
    ]
  },
  {
    id:'e_robbery',   name:'路遇劫匪',
    desc:'三名蒙面劫匪拦住去路，要你留下买路钱。',
    choices:[
      { text:'拔剑迎战',
        result:'你与劫匪大战一场，将其击退，缴获一些财物。',
        effect:{ gold:30, reputation:10, hp:-15, exp:20 } },
      { text:'乖乖交钱',
        result:'你忍气吞声，交出了一些银两。',
        effect:{ gold:-20, reputation:-5 } },
      { text:'假装服软，伺机逃跑',
        result:'你趁其不备，施展轻功逃脱。',
        effect:{ agility:5, exp:10 } },
      { text:'晓之以理，劝其从良',
        result:'劫匪中有人被你说动，放你离去，甚至有人愿意跟随你。',
        effect:{ morality:10, reputation:5, charm:5 },
        special:'recruit_bandit' },
    ]
  },
  {
    id:'e_secret_book', name:'发现秘籍',
    desc:'你在一处废弃的山洞中发现了一本残破的武功秘籍。',
    choices:[
      { text:'仔细研读，尝试修炼',
        result:'你花费数日研读，领悟了其中部分精髓。',
        effect:{ innerPower:15, perception:10, exp:30 } },
      { text:'带回去请高人指点',
        result:'你将秘籍带给了一位前辈，他为你详细讲解，收获颇丰。',
        effect:{ innerPower:10, perception:15, exp:25, reputation:5 } },
      { text:'据为己有，秘不示人',
        result:'你将秘籍藏好，日后慢慢研究。',
        effect:{ innerPower:8, evil:5 } },
      { text:'上交给门派',
        result:'门派对你大加赞赏，声望大增。',
        effect:{ reputation:20, morality:10 },
        require:'hasSect' },
    ]
  },
  {
    id:'e_beauty',    name:'邂逅佳人',
    desc:'你在客栈中遇到一位气质不凡的女子，她似乎遇到了麻烦。',
    choices:[
      { text:'挺身而出，仗义相助',
        result:'你帮助了她，她对你心生好感，留下了联系方式。',
        effect:{ morality:10, charm:8, reputation:10 },
        special:'meet_npc_beauty' },
      { text:'袖手旁观',
        result:'你冷眼旁观，女子用自己的方式解决了麻烦，对你投来鄙视的目光。',
        effect:{ reputation:-5 } },
      { text:'趁火打劫，要求报酬',
        result:'你帮助了她，但要求了报酬，她勉强答应，心中不满。',
        effect:{ gold:20, evil:5, charm:-5 } },
    ]
  },
  {
    id:'e_duel',      name:'江湖挑战',
    desc:'一名自称"快剑李三"的剑客拦住你，要与你比武。',
    choices:[
      { text:'接受挑战，正面迎战',
        result:'你与李三大战三十回合，胜负各半，互相佩服。',
        effect:{ swordSkill:8, reputation:10, exp:25, hp:-10 } },
      { text:'婉言谢绝，以礼相待',
        result:'李三见你谦逊有礼，反而对你刮目相看。',
        effect:{ morality:5, charm:5 } },
      { text:'出其不意，先发制人',
        result:'你突然出手，打了李三一个措手不及，但此举有失侠义。',
        effect:{ strength:5, evil:8, reputation:-5, exp:15 } },
    ]
  },
  {
    id:'e_orphan',    name:'孤儿求助',
    desc:'路边有一个衣衫褴褛的孤儿，向你乞讨食物。',
    choices:[
      { text:'慷慨解囊，给予帮助',
        result:'孤儿感激涕零，你心中也感到温暖。',
        effect:{ gold:-10, morality:15, reputation:8 } },
      { text:'给一点点，打发了事',
        result:'你给了一点零钱，孤儿道谢离去。',
        effect:{ gold:-3, morality:3 } },
      { text:'视而不见',
        result:'你冷漠地走过，孤儿的眼神让你心中不安。',
        effect:{ morality:-5 } },
      { text:'收留孤儿，带在身边',
        result:'你决定收留这个孤儿，他日后或许能成为你的得力助手。',
        effect:{ gold:-5, morality:20, reputation:10 },
        special:'recruit_orphan' },
    ]
  },
  {
    id:'e_poison',    name:'中毒危机',
    desc:'你不慎中了毒，毒性正在蔓延，需要立刻处理。',
    choices:[
      { text:'强行运功逼毒',
        result:'你强行运功，将毒素逼出大半，但内力大损。',
        effect:{ hp:-20, innerPower:-15 } },
      { text:'寻找解药',
        result:'你找到了一位郎中，花费银两解了毒。',
        effect:{ gold:-30, hp:-5 } },
      { text:'以毒攻毒，服下另一种毒药',
        result:'险中求胜，毒素相互抵消，你安然无恙，还意外提升了抗毒能力。',
        effect:{ endurance:15, luck:5, hp:-5 } },
    ]
  },
  {
    id:'e_spy',       name:'发现奸细',
    desc:'你无意中发现一名蒙古奸细正在刺探情报。',
    choices:[
      { text:'立刻擒拿，扭送官府',
        result:'你将奸细擒获，官府重重嘉奖。',
        effect:{ gold:40, reputation:20, morality:10 } },
      { text:'暗中跟踪，摸清底细',
        result:'你跟踪奸细，发现了一个蒙古情报网络，获得重要情报。',
        effect:{ perception:10, reputation:15, exp:20 } },
      { text:'假装不知，放其离去',
        result:'你选择明哲保身，奸细顺利离去。',
        effect:{ morality:-10 } },
      { text:'与奸细接触，为己所用',
        result:'你与奸细达成协议，获得了一些秘密情报，但此举有损名节。',
        effect:{ gold:60, evil:15, reputation:-10 },
        require:'evil' },
    ]
  },
  {
    id:'e_tournament', name:'武林大会',
    desc:'江湖上举办了一场武林大会，高手云集，你是否参加？',
    choices:[
      { text:'参加比武，一展身手',
        result:'你在比武中表现出色，名声大噪。',
        effect:{ reputation:30, exp:40, hp:-20 } },
      { text:'以观众身份旁观学习',
        result:'你在旁观中领悟了不少武学精髓。',
        effect:{ perception:15, exp:20 } },
      { text:'趁乱结交各路英雄',
        result:'你广结善缘，认识了不少江湖朋友。',
        effect:{ charm:10, reputation:15 } },
    ]
  },
  {
    id:'e_ancient_tomb', name:'古墓奇遇',
    desc:'你在山中迷路，误入一处古墓，墓中机关重重，却也藏有宝物。',
    choices:[
      { text:'小心探索，寻找出路',
        result:'你触发了一处机关，但也发现了一本武功秘籍。',
        effect:{ innerPower:20, hp:-10, exp:30 } },
      { text:'原路返回，不贪宝物',
        result:'你安全退出，虽无所获，但保住了性命。',
        effect:{ morality:5 } },
      { text:'大胆深入，寻找传说中的宝藏',
        result:'你深入古墓，历经险阻，终于找到了一件神兵利器！',
        effect:{ hp:-30, exp:50 },
        special:'find_weapon' },
    ]
  },
  {
    id:'e_master',    name:'高人指点',
    desc:'一位白眉老者观察你练功许久，开口道："你的武功路子不对，可愿听老夫指点？"',
    choices:[
      { text:'虚心请教，洗耳恭听',
        result:'老者为你纠正了武功中的错误，你的修炼速度大增。',
        effect:{ innerPower:15, perception:10, exp:25 } },
      { text:'婉言谢绝，自有主张',
        result:'老者摇头叹气，飘然而去。',
        effect:{} },
      { text:'请老者收你为徒',
        result:'老者沉吟片刻，说："你有此心，老夫便考考你。"',
        effect:{ perception:5 },
        special:'try_apprentice' },
    ]
  },
],

// ─────────────────────────────────────────────
//  境界系统
// ─────────────────────────────────────────────
REALMS: [
  { id:'r_mortal',    name:'后天境',   minPower:0,    desc:'普通人，尚未入门' },
  { id:'r_xiantian',  name:'先天境',   minPower:100,  desc:'内力已入先天，武功初成' },
  { id:'r_zongshi',   name:'宗师境',   minPower:250,  desc:'武功已臻宗师，江湖一流高手' },
  { id:'r_jueding',   name:'绝顶境',   minPower:500,  desc:'武功绝顶，天下罕有敌手' },
  { id:'r_legend',    name:'传说境',   minPower:800,  desc:'武林传说，名垂千古' },
],

// ─────────────────────────────────────────────
//  K: 物品/药材库
//  type: herb=草药, pill=丹药, food=食物, material=材料, weapon=武器
//  effect: 使用时的效果
//  buyPrice: 商店购买价，0=不可购买
//  sellPrice: 出售价格
// ─────────────────────────────────────────────
ITEMS: [
  // ── 草药 ──
  { id:'i_herb',      name:'普通草药',  type:'herb',
    desc:'山中常见草药，可恢复少量体力，也是许多丹药的基础材料。',
    effect:{ energy:15 }, buyPrice:5, sellPrice:2,
    icon:'🌿' },
  { id:'i_ginseng',   name:'百年人参',  type:'herb',
    desc:'深山中生长百年的人参，药力极为强劲，可大幅恢复体力和内力。',
    effect:{ energy:40, innerPower:5 }, buyPrice:80, sellPrice:40,
    icon:'🌱' },
  { id:'i_lingzhi',   name:'千年灵芝',  type:'herb',
    desc:'传说中的仙草，极为罕见，服用后内力大增，甚至可以突破瓶颈。',
    effect:{ energy:30, innerPower:15, hp:20 }, buyPrice:200, sellPrice:100,
    icon:'🍄' },
  { id:'i_xuelian',   name:'雪莲花',    type:'herb',
    desc:'生长于雪山之巅的奇花，清热解毒，可解大多数毒素。',
    effect:{ energy:20, curePoison:true }, buyPrice:60, sellPrice:30,
    icon:'🌸' },
  { id:'i_wudu',      name:'五毒草',    type:'herb',
    desc:'含有剧毒的草药，可用于炼制毒药，也可少量入药治疗顽疾。',
    effect:{ energy:5 }, buyPrice:15, sellPrice:8,
    icon:'🌾' },

  // ── 丹药 ──
  { id:'i_huisheng',  name:'回生丹',    type:'pill',
    desc:'名医所制，服用后可迅速恢复大量体力，战斗中的救命良药。',
    effect:{ energy:60, hp:30 }, buyPrice:120, sellPrice:60,
    icon:'💊' },
  { id:'i_peiyuan',   name:'培元丹',    type:'pill',
    desc:'专门培补元气的丹药，长期服用可增强内力根基。',
    effect:{ energy:30, innerPower:10 }, buyPrice:80, sellPrice:40,
    icon:'🔴' },
  { id:'i_jiedu',     name:'解毒丹',    type:'pill',
    desc:'可解百毒的神丹，江湖行走必备之物。',
    effect:{ curePoison:true, energy:10 }, buyPrice:50, sellPrice:25,
    icon:'🟢' },
  { id:'i_dali',      name:'大力丸',    type:'pill',
    desc:'服用后短时间内力量大增，但过后会有虚弱感。',
    effect:{ strength:15, energy:-10, duration:1 }, buyPrice:40, sellPrice:20,
    icon:'🟡' },
  { id:'i_jiuhua',    name:'九花玉露丸', type:'pill',
    desc:'极品丹药，传说是全真教秘方所制，服用后内力修为大进。',
    effect:{ energy:50, innerPower:20, hp:20 }, buyPrice:300, sellPrice:150,
    icon:'⚪' },

  // ── 食物 ──
  { id:'i_food',      name:'干粮',      type:'food',
    desc:'普通干粮，可以充饥恢复少量体力。',
    effect:{ energy:10 }, buyPrice:2, sellPrice:1,
    icon:'🍞' },
  { id:'i_wine',      name:'好酒',      type:'food',
    desc:'一壶好酒，喝下去心情大好，但可能影响身法。',
    effect:{ energy:15, agility:-5, duration:1 }, buyPrice:10, sellPrice:5,
    icon:'🍶' },
  { id:'i_meat',      name:'烤全羊',    type:'food',
    desc:'大块吃肉，大碗喝酒，江湖豪迈！恢复体力效果极佳。',
    effect:{ energy:25, strength:5, duration:1 }, buyPrice:20, sellPrice:10,
    icon:'🍖' },

  // ── 材料 ──
  { id:'i_ironore',   name:'精铁矿石',  type:'material',
    desc:'打造兵器的上等材料，铁匠铺收购价格不错。',
    effect:{}, buyPrice:0, sellPrice:15,
    icon:'⚙️' },
  { id:'i_jade',      name:'碧玉',      type:'material',
    desc:'上等碧玉，可用于制作护身符，也可出售给珠宝商。',
    effect:{}, buyPrice:0, sellPrice:50,
    icon:'💎' },
],

// ─────────────────────────────────────────────
//  K: 商店库存（不同地点有不同商品）
// ─────────────────────────────────────────────
SHOPS: {
  '小镇': ['i_herb', 'i_food', 'i_wine', 'i_jiedu'],
  '江湖': ['i_herb', 'i_food', 'i_huisheng', 'i_jiedu', 'i_dali'],
  '襄阳': ['i_herb', 'i_ginseng', 'i_huisheng', 'i_peiyuan', 'i_jiedu', 'i_food', 'i_meat', 'i_wine'],
  '古墓': [],
  '蒙古大营': [],
},

// ─────────────────────────────────────────────
//  L: 称号系统
//  condition: 触发条件（满足任意一项即可获得）
//  effect: 称号带来的被动效果（影响NPC好感和事件概率）
//  tier: 1=普通, 2=稀有, 3=传奇
// ─────────────────────────────────────────────
TITLES: [
  // ── 声望类 ──
  { id:'tl_wanderer',   name:'江湖游侠',  tier:1,
    desc:'初入江湖，小有名气的游侠。',
    condition:{ reputation:20 },
    effect:{ npcFavorMod:5, questRewardMod:0 } },
  { id:'tl_hero',       name:'一方豪杰',  tier:1,
    desc:'在一方地界颇有名望，百姓口耳相传。',
    condition:{ reputation:60 },
    effect:{ npcFavorMod:10, questRewardMod:5 } },
  { id:'tl_famous',     name:'名震江湖',  tier:2,
    desc:'名声响彻江湖，无论走到哪里都有人认识你。',
    condition:{ reputation:120 },
    effect:{ npcFavorMod:20, questRewardMod:10, eventMod:{ positive:10 } } },
  { id:'tl_legend',     name:'武林传奇',  tier:3,
    desc:'你的名字已成为传奇，江湖中无人不知无人不晓。',
    condition:{ reputation:250 },
    effect:{ npcFavorMod:35, questRewardMod:20, eventMod:{ positive:20 } } },

  // ── 武功类 ──
  { id:'tl_swordsman',  name:'剑客',      tier:1,
    desc:'以剑闻名，剑法颇有造诣。',
    condition:{ swordSkill:40 },
    effect:{ combatBonus:5 } },
  { id:'tl_swordmaster',name:'剑道高手',  tier:2,
    desc:'剑法已臻化境，出剑如行云流水。',
    condition:{ swordSkill:100 },
    effect:{ combatBonus:15, npcFavorMod:10 } },
  { id:'tl_innermaster',name:'内功宗师',  tier:2,
    desc:'内力深厚，已达宗师境界，修炼速度远超常人。',
    condition:{ innerPower:150 },
    effect:{ trainingBonus:20, combatBonus:10 } },

  // ── 道德类 ──
  { id:'tl_righteous',  name:'正道侠士',  tier:1,
    desc:'行事光明磊落，是正道中人的楷模。',
    condition:{ morality:40 },
    effect:{ npcFavorMod:15, eventMod:{ positive:5 } } },
  { id:'tl_greatxia',   name:'侠之大者',  tier:3,
    desc:'为国为民，侠之大者。郭大侠亲口称赞的称号。',
    condition:{ morality:80, reputation:150 },
    effect:{ npcFavorMod:40, questRewardMod:15, eventMod:{ positive:25 } } },
  { id:'tl_evil',       name:'魔头',      tier:1,
    desc:'作恶多端，江湖中人人喊打。',
    condition:{ evil:40 },
    effect:{ npcFavorMod:-20, eventMod:{ negative:10 } } },
  { id:'tl_demon',      name:'一代魔头',  tier:2,
    desc:'恶名昭著，令人闻风丧胆，正道中人见之必诛。',
    condition:{ evil:80 },
    effect:{ npcFavorMod:-35, combatBonus:10, eventMod:{ negative:20 } } },

  // ── 任务类 ──
  { id:'tl_guardian',   name:'守城英雄',  tier:2,
    desc:'参与守卫襄阳，被百姓称为守城英雄。',
    condition:{ questDone:'q_defend' },
    effect:{ npcFavorMod:20, morality:5 } },
  { id:'tl_doctor',     name:'悬壶济世',  tier:1,
    desc:'多次帮助医治病患，被称为悬壶济世的大夫。',
    condition:{ questDone:'q_medicine3' },
    effect:{ npcFavorMod:15, itemDiscountMod:10 } },
  { id:'tl_spy',        name:'影子刺客',  tier:2,
    desc:'多次完成潜入任务，行踪飘忽如影随形。',
    condition:{ questDone:'q_spy' },
    effect:{ combatBonus:8, stealthBonus:20 } },

  // ── 财富类 ──
  { id:'tl_rich',       name:'富甲一方',  tier:1,
    desc:'家财万贯，在江湖中颇有财力。',
    condition:{ gold:500 },
    effect:{ itemDiscountMod:5, npcFavorMod:5 } },
  { id:'tl_pauper',     name:'穷困潦倒',  tier:1,
    desc:'身无分文，连饭都吃不起，江湖路难行。',
    condition:{ goldBelow:10 },
    effect:{ npcFavorMod:-5, questRewardMod:-5 } },
],

// ─────────────────────────────────────────────
//  结局
// ─────────────────────────────────────────────
ENDINGS: [
  { id:'end_hero',    name:'侠之大者',
    condition:{ morality:80, reputation:200, innerPower:300 },
    desc:'你以侠义之心行走江湖，最终成为一代大侠，名垂青史，与郭靖并称"双侠"。' },
  { id:'end_demon',   name:'魔教教主',
    condition:{ evil:80, innerPower:300, sectRank:{ sect:'s_mingjiao', rank:9 } },
    desc:'你走上邪道，凭借强横武力成为魔教教主，令江湖闻风丧胆。' },
  { id:'end_hermit',  name:'隐世高人',
    condition:{ innerPower:400, reputation:100, morality:50 },
    desc:'你看破红尘，隐居山林，成为传说中的世外高人，偶尔出山指点后辈。' },
  { id:'end_general', name:'护国将军',
    condition:{ reputation:150, strength:200, sectRank:{ sect:'s_court', rank:5 } },
    desc:'你投身朝廷，凭借赫赫战功成为护国将军，为守卫家园立下汗马功劳。' },
  { id:'end_sword',   name:'剑道宗师',
    condition:{ swordSkill:300, innerPower:200, reputation:150 },
    desc:'你一生痴迷剑道，终于悟出剑道至理，成为天下第一剑客，独孤求败。' },
  { id:'end_love',    name:'归隐田园',
    condition:{ charm:100, morality:40, followers:1 },
    desc:'你找到了心爱之人，携手归隐田园，过上了平静幸福的生活。' },
],

};
